### VErificar se o servidor esta no ar
GET http://localhost:3333/ping


### Listar todos as notas
GET http://localhost:3333/annotations


### Inserir uma nota
POST http://localhost:3333/annotations
Content-Type: application/json

{
    "title": "Oficina",
    "notes": "Levar carro para trocar oleo de freio",
    "priority": false
}


### Deletar uma nota
DELETE  http://localhost:3333/annotations/4


