### VErificar se o servidor esta no ar
GET http://localhost:3333/ping


### Listar todas as notas
GET http://localhost:3333/annotations


### Inserir uma nota
POST http://localhost:3333/annotations
Content-Type: application/json

{
    "title": "Trabalho Teste",
    "notes": "Levar notebook para o escritório",
    "priority": true
}


### Deletar uma nota
DELETE http://localhost:3333/annotations/12


### Alterar uma nota
PUT http://localhost:3333/annotations/5
Content-Type: application/json

{
    "notes": "Levar carro para trocar oleo e pastilha de freio "
}


### Buscar todas as prioridades iguais a true
GET http://localhost:3333/priorities?priority=true


### Trocar prioridade da nota
PUT http://localhost:3333/priorities/5